name: Build Package to use ncc
on: [pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Check EOF newlines
        uses: gps/newline-at-eof@kunal/exclude-executable-files
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_FILE_PATTERNS: |
            [
              "dist/.*",
              "package-lock.json"
            ]
          COMMIT_MESSAGE: 'Fixed EOF Newline'
