name: Build Package to use ncc
on: [pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest
    env:
      IGNORE_PATHS_STRING: ${{ 'build/ package-lock.json' }}

    steps:
      - uses: actions/checkout@v2
      - name: Build node js module
        uses: gps/ncc-gha@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_PATHS: ${{ env.IGNORE_PATHS_STRING }}
