name: Build Package to use ncc
on: [pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check EOF newlines
        uses: gps/newline-at-eof@kunal/ch1768-add-action-files
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_FILE_PATTERNS: |
            [
              "dist/.*",
              "package-lock.json"
            ]
          COMMIT_MESSAGE: 'Fixed EOF Newline'




