name: Build Package to use ncc
on: [pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Check EOF newlines
        uses: gps/newline-at-eof
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_FILE_PATTERNS: |
            [
              "dist/.*",
              "package-lock.json"
            ]
          COMMIT_AND_PUSH_CHANGES: false
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format code
